export interface CurriculumSubject {
  id: string;
  title: string;
  year?: string;
  category: 'elementary' | 'secondary';
  color: string;
  iconType: string;
  grades: string;
  description: string;
  linkUrl: string;
}

export const CURRICULUM_DATA: CurriculumSubject[] = [
  // ================= ELEMENTARY CURRICULUM (K-8) =================
  {
    id: 'kindergarten',
    title: 'Kindergarten',
    year: '2016',
    category: 'elementary',
    color: '#B91C1C', // Red
    iconType: 'kindergarten',
    grades: 'Kindergarten (JK & SK)',
    description: 'Play-based inquiry learning designed to support young children in developing emotional, social, cognitive, and physical foundations.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/kindergarten',
  },
  {
    id: 'the-arts-elementary',
    title: 'The Arts',
    year: '2009',
    category: 'elementary',
    color: '#C2410C', // Orange / Amber
    iconType: 'arts',
    grades: 'Grades 1–8',
    description: 'Encompasses Dance, Drama, Music, and Visual Arts to cultivate creative expression, aesthetic perception, and critical thinking.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-arts',
  },
  {
    id: 'fsl-elementary',
    title: 'French as a Second Language',
    year: '2013',
    category: 'elementary',
    color: '#6B21A8', // Deep Purple
    iconType: 'fsl',
    grades: 'Grades 1–8',
    description: 'Core, Extended, and French Immersion programs developing communication, listening, speaking, reading, and intercultural awareness.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-fsl',
  },
  {
    id: 'health-pe-elementary',
    title: 'Health and Physical Education',
    year: '2019',
    category: 'elementary',
    color: '#9D174D', // Pink / Magenta
    iconType: 'health',
    grades: 'Grades 1–8',
    description: 'Active living, movement competence, healthy development, mental health literacy, and personal safety awareness.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-health-and-physical-education',
  },
  {
    id: 'language-elementary',
    title: 'Language',
    year: '2023',
    category: 'elementary',
    color: '#44403C', // Slate Charcoal
    iconType: 'language',
    grades: 'Grades 1–8',
    description: 'Modernized, evidence-based curriculum focused on foundational reading, phonics, vocabulary, writing fluency, and digital literacy.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-language',
  },
  {
    id: 'mathematics-elementary',
    title: 'Mathematics',
    year: '2020',
    category: 'elementary',
    color: '#0369A1', // Ocean Blue
    iconType: 'math',
    grades: 'Grades 1–8',
    description: 'Modernized curriculum covering Number, Algebra (including coding), Data, Spatial Sense, Financial Literacy, and SEL in Math.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-mathematics',
  },
  {
    id: 'native-languages-elementary',
    title: 'Native Languages',
    year: '2001',
    category: 'elementary',
    color: '#854D0E', // Bronze Ochre
    iconType: 'native',
    grades: 'Grades 1–8',
    description: 'Promoting the revitalization, appreciation, oral tradition, and fluency of Indigenous languages and cultural heritage.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-native-languages',
  },
  {
    id: 'science-tech-elementary',
    title: 'Science and Technology',
    year: '2022',
    category: 'elementary',
    color: '#0F766E', // Emerald / Teal
    iconType: 'science',
    grades: 'Grades 1–8',
    description: 'Hands-on STEM curriculum integrating coding, engineering design processes, emerging technology, and climate literacy.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-science-and-technology',
  },
  {
    id: 'social-studies-elementary',
    title: 'Social Studies, History, and Geography',
    category: 'elementary',
    color: '#15803D', // Forest Green
    iconType: 'social',
    grades: 'Grades 1–8 (Social Studies 1–6, History & Geo 7–8)',
    description: 'Inquiry-based exploration of Canadian identity, Indigenous histories, global citizenship, physical geography, and democratic systems.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/elementary-sshg',
  },

  // ================= SECONDARY CURRICULUM (9-12) =================
  {
    id: 'asl-secondary',
    title: 'American Sign Language as a Second Language',
    year: '2021',
    category: 'secondary',
    color: '#6B21A8',
    iconType: 'asl',
    grades: 'Grades 9–12',
    description: 'American Sign Language credit curriculum for visual-gestural communication, Deaf culture, and linguistic appreciation.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-asl',
  },
  {
    id: 'the-arts-secondary',
    title: 'The Arts',
    year: '2010',
    category: 'secondary',
    color: '#C2410C',
    iconType: 'arts',
    grades: 'Grades 9–12',
    description: 'High school courses in Dance, Dramatic Arts, Integrated Arts, Music, Visual Arts, and Media Arts for studio & career pathways.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-arts',
  },
  {
    id: 'business-secondary',
    title: 'Business Studies',
    category: 'secondary',
    color: '#0284C7',
    iconType: 'business',
    grades: 'Grades 9–12',
    description: 'Accounting, Marketing, Entrepreneurship, International Business, Business Leadership, and Financial Management courses.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-business-studies',
  },
  {
    id: 'canadian-world-studies-secondary',
    title: 'Canadian and World Studies',
    category: 'secondary',
    color: '#047857',
    iconType: 'cws',
    grades: 'Grades 9–12',
    description: 'Civics and Citizenship, Geography of Canada, Canadian and World History, Law, Politics, and Economics courses.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-cws',
  },
  {
    id: 'classical-languages-secondary',
    title: 'Classical Studies and International Languages',
    year: '2016',
    category: 'secondary',
    color: '#854D0E',
    iconType: 'classical',
    grades: 'Grades 9–12',
    description: 'Ancient Greek, Latin, Classical Civilization, and international world languages for secondary credit.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-classical-and-international-languages',
  },
  {
    id: 'computer-studies-secondary',
    title: 'Computer Studies',
    category: 'secondary',
    color: '#0284C7',
    iconType: 'computer',
    grades: 'Grades 10–12',
    description: 'Introduction to Computer Studies, Computer Science (ICS3U/ICS4U), and modern Software Engineering principles.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-computer-studies',
  },
  {
    id: 'coop-secondary',
    title: 'Cooperative Education',
    year: '2018',
    category: 'secondary',
    color: '#0D9488',
    iconType: 'coop',
    grades: 'Grades 11–12',
    description: 'Work-integrated experiential learning connecting classroom knowledge with real workplace environments and future careers.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-cooperative-education',
  },
  {
    id: 'english-secondary',
    title: 'English',
    category: 'secondary',
    color: '#44403C',
    iconType: 'english',
    grades: 'Grades 9–12',
    description: 'De-streamed Grade 9 English (ENL1W), Grade 10 English (ENG2D), and senior University/College preparation courses.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-english',
  },
  {
    id: 'esl-eld-secondary',
    title: 'English As a Second Language and English Literacy Development',
    year: '2007',
    category: 'secondary',
    color: '#0D9488',
    iconType: 'esl',
    grades: 'Grades 9–12',
    description: 'Comprehensive ESL and ELD courses supporting multilingual language learners and newcomer high school students.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-esl-and-eld',
  },
  {
    id: 'first-nations-secondary',
    title: 'First Nations, Métis, and Inuit Studies',
    year: '2019',
    category: 'secondary',
    color: '#0284C7',
    iconType: 'fnmi',
    grades: 'Grades 9–12',
    description: 'In-depth courses exploring Indigenous histories, worldviews, governance, sovereignty, creative arts, and legal treaties.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-first-nations-metis-and-inuit-studies',
  },
  {
    id: 'fsl-secondary',
    title: 'French as a Second Language',
    year: '2014',
    category: 'secondary',
    color: '#6B21A8',
    iconType: 'fsl',
    grades: 'Grades 9–12',
    description: 'Core French, Extended French, and French Immersion credit courses fostering advanced oral and written bilingualism.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-fsl',
  },
  {
    id: 'guidance-secondary',
    title: 'Guidance and Career Education',
    category: 'secondary',
    color: '#C2410C',
    iconType: 'guidance',
    grades: 'Grades 9–12',
    description: 'Career Studies (GLC2O), learning strategies, life choices, and personal post-secondary transition planning.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-guidance',
  },
  {
    id: 'health-pe-secondary',
    title: 'Health and Physical Education',
    year: '2015',
    category: 'secondary',
    color: '#9D174D',
    iconType: 'health',
    grades: 'Grades 9–12',
    description: 'Active living, physical fitness conditioning, personal safety, mental health literacy, and healthy interpersonal relationships.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-health-and-physical-education',
  },
  {
    id: 'interdisciplinary-secondary',
    title: 'Interdisciplinary Studies',
    year: '2002',
    category: 'secondary',
    color: '#BE185D',
    iconType: 'interdisciplinary',
    grades: 'Grades 11–12',
    description: 'Cross-disciplinary research, inquiry methods, and collaborative project courses combining multiple academic subjects.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-interdisciplinary-studies',
  },
  {
    id: 'mathematics-secondary',
    title: 'Mathematics',
    category: 'secondary',
    color: '#0369A1',
    iconType: 'math',
    grades: 'Grades 9–12',
    description: 'De-streamed Grade 9 Math (MTH1W), Functions (MCR3U), Advanced Functions (MHF4U), and Calculus & Vectors (MCV4U).',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-mathematics',
  },
  {
    id: 'native-languages-secondary',
    title: 'Native Languages',
    category: 'secondary',
    color: '#854D0E',
    iconType: 'native',
    grades: 'Grades 9–12',
    description: 'Secondary credit courses deepening communicative competence, cultural storytelling, and literacy in Indigenous languages.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-native-languages',
  },
  {
    id: 'science-secondary',
    title: 'Science',
    category: 'secondary',
    color: '#0F766E',
    iconType: 'science',
    grades: 'Grades 9–12',
    description: 'Grade 9 De-streamed Science (SNC1W), Grade 10 Science (SNC2D), and senior academic Biology, Chemistry, and Physics.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-science',
  },
  {
    id: 'social-sciences-secondary',
    title: 'Social Sciences and Humanities',
    year: '2013',
    category: 'secondary',
    color: '#DC2626',
    iconType: 'social-sciences',
    grades: 'Grades 9–12',
    description: 'Equity studies, family studies, world religions, philosophy, psychology, anthropology, and social justice courses.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-social-sciences-and-humanities',
  },
  {
    id: 'tech-secondary',
    title: 'Technological Education',
    category: 'secondary',
    color: '#0F766E',
    iconType: 'tech',
    grades: 'Grades 9–12',
    description: 'Communications technology, computer engineering, construction, manufacturing, design, robotics, and transportation.',
    linkUrl: 'https://www.dcp.edu.gov.on.ca/en/curriculum/secondary-technological-education',
  },
];
